
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - istacon.org
  resources:
  - conferencetalks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - istacon.org
  resources:
  - conferencetalks/finalizers
  verbs:
  - update
- apiGroups:
  - istacon.org
  resources:
  - conferencetalks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - istacon.org
  resources:
  - speakers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - istacon.org
  resources:
  - speakers/finalizers
  verbs:
  - update
- apiGroups:
  - istacon.org
  resources:
  - speakers/status
  verbs:
  - get
  - patch
  - update
