apiVersion: istacon.org/v1
kind: ConferenceTalk
metadata:
  name: kubernetes-extensibility
spec:
  title: "Next phases of K8S: From system management towards a platform to build applications and services"
  summary: |
    This talk will present Kubernetes not only as a workload orchestration environment,
    but as a platform for hosting and serving applications and services itself.
  speakerId: anton-sankov